### ISSUE TITLE
Error from chocolatey: Exception calling "Install" with "0" argument(s)

### ISSUE THREAD

**Issue by SurajGupta** [mwrock/boxstarter#79] opened 2015-04-01 15:01 UTC
I'm getting the following exception right after my package calls `Install-WindowsUpdate`.  It's not clear to me whether this was caused by that call, by any wrap-up work that Boxstarter is doing prior to restarting, or perhaps by an earlier call.

    ...
    [2015-04-01T07:52:25.9695300-07:00:::PID 2368] +++ Boxstarter starting Install 37 of 47 updates: Security Update for Windows 8.1 for x64-based Systems (KB3035132)
    [2015-04-01T07:52:31.2820322-07:00:::PID 2368] Boxstarter: Checking for Pending reboot
    [2015-04-01T07:52:31.3914055-07:00:::PID 2368] Boxstarter: Detected Pending reboot
    [2015-04-01T07:52:31.4070302-07:00:::PID 2368] @{Computer=SANDBOX; CBServicing=True; WindowsUpdate=True; PendFileRename=False; RebootPending=True}
    [2015-04-01T07:52:31.4070302-07:00:::PID 2368] Boxstarter: writing restart file
    [2015-04-01T07:52:31.4070302-07:00:::PID 2368] Boxstarter: writing restart file
    [2015-04-01T07:52:33.6570296-07:00:::PID 2368] Finished installing 'temp_BoxstarterPackage' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
    [2015-04-01T07:52:33.7039050-07:00:::PID 2368] Boxstarter: Exit Code: 0
    [2015-04-01T07:52:33.7039050-07:00:::PID 2368] Boxstarter: There was an error calling chocolatey
    [2015-04-01T07:52:33.8289042-07:00:::PID 2368] Error from chocolatey: 
    
    ErrorRecord                 : Exception calling "Install" with "0" argument(s):
                                   "Exception from HRESULT: 0x80240016"
    StackTrace                  :    at System.Management.Automation.ComMethod.Invo
                                  keMethod(PSMethod method, Object[] arguments)
                                     at System.Management.Automation.Adapter.BaseMe
                                  thodInvoke(PSMethod method, PSMethodInvocationCon
                                  straints invocationConstraints, Object[] argument
                                  s)
                                     at Install-Update(Closure , FunctionContext )
    WasThrownFromThrowStatement : False
    Message                     : Exception calling "Install" with "0" argument(s):
                                   "Exception from HRESULT: 0x80240016"
    Data                        : {}
    InnerException              : System.Reflection.TargetInvocationException: Exce
                                  ption has been thrown by the target of an invocat
                                  ion. ---> System.Runtime.InteropServices.COMExcep
                                  tion: Exception from HRESULT: 0x80240016
                                     --- End of inner exception stack trace ---
                                     at System.RuntimeType.InvokeDispMethod(String 
                                  name, BindingFlags invokeAttr, Object target, Obj
                                  ect[] args, Boolean[] byrefModifiers, Int32 cultu
                                  re, String[] namedParameters)
                                     at System.RuntimeType.InvokeMember(String name
                                  , BindingFlags bindingFlags, Binder binder, Objec
                                  t target, Object[] providedArgs, ParameterModifie
                                  r[] modifiers, CultureInfo culture, String[] name
                                  dParams)
                                     at System.Management.Automation.ComMethod.Invo
                                  keMethod(PSMethod method, Object[] arguments)
    TargetSite                  : Void CheckActionPreference(System.Management.Auto
                                  mation.Language.FunctionContext, System.Exception
                                  )
    HelpLink                    : 
    Source                      : System.Management.Automation
    HResult                     : -2146233087

**Comment by mwrock** [comment] 2015-04-01 20:28
This is a windows update error that means that something else is trying to run wndows update. Boxstarter makes an effort to ensure this does not happen by turning off the update service before it begins the update run. However this can be subverted if either you manually start the service (which I am guessing is not the case here) or perhaps some other process on your machine either turns this on or goes off to install updates on its own. I have not seen this happen before but can certainly envision enterprise scenarios where this could happen.

I do think there are extra efforts boxstarter could make to prevent this from happening. So I will keep this open to track that.

**Comment by SurajGupta** [comment] 2015-04-01 22:28
It's odd because I'm using a vanilla/clean install of Windows 8.1.  I think there might be something else going on here.  Prior to my call to Install-WindowsUpdate, there's not much happening.  Any ideas on how I can debug this further?

**Comment by mwrock** [comment] 2015-04-02 04:10
After doing more research on that error code, it appears that the root issue is that windows cannot access the user token. If something else is trying to update the system that can cause this error, or if the user has been logged in for a long time.

A couple questions:

1. Is the machine domain joined?
2. how are you provisioning this machine? Is this a VM or bare metal?Are you running boxstarter right after installing an ISO?

**Comment by kmeinster** [comment] 2015-04-02 10:48
I'm getting the same result, I'm try to automate a build process for windows images based on https://github.com/mitchellh/packer which fails because of a boxstarter error. The same as above, in my case I'm using a "don't reboot" option, which is needed in order for packer to understand what is happening (a sudden reboot will abort the build). Any idea on what the REAL reason is of this error?

It's based on a vanilla windows 2012 R2 iso from mickeysoft, with some chocolatey installs (notepad, sys internals etc).

The boxstarter itself is called via a chef-solo (called by packer) unfortunately it's WinRM so updating windows is kind of a hazard (task scheduler doesn't really work either because with that our builder has no idea what is happening).

`  
  amazon-windows-ebs: + Boxstarter starting Install 10 of 16 updates: Security Update for Windows Server 2012 R2 (KB3002657)
   - amazon-windows-ebs: There is either an update in progress or there is a pending reboot blocking the install.
   - amazon-windows-ebs: If you are using the Bootstrapper or Chocolatey module, try using:
   - amazon-windows-ebs: if(Test-PendingReboot){Invoke-Reboot}
   - amazon-windows-ebs: This will perform a reboot if reboots are pending.
   - amazon-windows-ebs: Boxstarter: There were problems installing updates: Exception calling "Install" with "0" argument(s): "Exception from HRESULT: 0x80240016"
   - amazon-windows-ebs: Finished installing 'temp_BoxstarterPackage' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
   - amazon-windows-ebs: [WIN-BKGOUE280CA]+ Boxstarter finished Calling Chocolatey to install temp_BoxstarterPackage. This may take several minutes to complete... 00:04:41.6650723
   - amazon-windows-ebs: [WIN-BKGOUE280CA]Boxstarter: Enabling Automatic Updates from Windows Update
   - amazon-windows-ebs: ERROR SUMMARY:
   - amazon-windows-ebs: #1)
   - amazon-windows-ebs: STDERR: #< CLIXML`

**Comment by SurajGupta** [comment] 2015-04-02 12:37
@mwrock - to answer your questions:
1. the machine is not domain joined
2. This is a VM in Hyper-V.  It was created using a Windows 8.1 ISO. A few months ago I installed the OS, applied all windows updates that were available at the time, shutdown the VM and took a snapshot.  I am restoring that original snapshot and then performing my BoxStarter install.  Since the snapshot was taken a few months ago, the box is now behind on Windows Updates.

**Comment by mwrock** [comment] 2015-04-02 16:18
@SurajGupta thanks for this info. A few more questions:

1. Are you running boxstarter locally on the vm?
2. If so, are you invoking it via the web based installer or calling `Install-BoxstarterPackage`?
3. If not, are you using Boxstarter.HyperV or calling `Install-BoxstarterPackage` directly with `-ComputerName`?

Thanks!

**Comment by mwrock** [comment] 2015-04-02 16:22
@kmeinster Just curious if you are you using the Boxstarter cookbook from chef-solo.

**Comment by mwrock** [comment] 2015-04-02 16:25
To both @SurajGupta and @kmeinster could you supply a gist of your complete boxstarter log? It is located at `$env:LocalAppData\Boxstarter\Boxstarter.log`

I'd really like to figure out how to prevent this error. Its pretty tough to reproduce so more info is good. Thanks!

**Comment by SurajGupta** [comment] 2015-04-02 17:00
@mwrock - To answer your questions:
1. yes, I am running it locally on the VM.
2. I am calling Install-BoxstarterPackage

In fact, here's the repo with exactly what I'm running: https://github.com/SurajGupta/BoxBot
I call Bootstrap and that takes care of the rest.  The last line in Boostrap() is Install-BoxstarterPackage.  The package itself is defined in BuildBox.ps1.  You'll see the call to Install-WindowsUpdate on line 22 of that file.  My code is fairly well-documented, so you can probably just read the comments to understand the workflow - it's all pretty straight-forward.

Here's the Gist with the log file: https://gist.github.com/SurajGupta/544c55cee047ca71f7a6
The error is on line 397

**Comment by kmeinster** [comment] 2015-04-02 18:22
@mwrock will do too

Yes i'm using the basic cookbook, just ripped out the installables (fiddler etc) to test. ill see if I can make a better test setup tonight and without packer (but with winrm) so i can do some more research.

Will put in a gist later on tonight for the logs.

**Comment by kmeinster** [comment] 2015-04-02 22:34
https://gist.github.com/kmeinster/6504318ce0b0710ff35a

The packer output is a bit blurry to read.

**Comment by mwrock** [comment] 2015-04-03 08:52
I think I may have a fix for this and hope to release tomorrow.

**Comment by SurajGupta** [comment] 2015-04-03 13:53
that's great!   Would be interested/curious as to what found.

**Comment by kmeinster** [comment] 2015-04-03 15:02
@mwrock Cool man, let us know when you need testing ;-)

**Comment by mwrock** [comment] 2015-04-05 03:48
ok. I just released 2.4.205 which I am hoping fixes this. It addresses a few bug fixes, 2 of which impact this issue and 1 in particular I think fixws both of your use cases. The fix that impacts this but is lesslikey to be a factor for both of you is that the windows update service is now restarted before before boxstarter begins the search for updates. This would address scenarios where windows might have already started updates in the background. However, I doubt this affected @SurajGupta since he had installed several installs successfully before it failed.

What I think fixes this for you is that therre has been for some time now a specific error handling case for HRESULT: 0x80240016 which I had forgotten about (I dont typically remember specific HRESULTs). The problem is that althogh the error is effectively handled, the error still gets bubbled up at the end of the run. This is really an aesthetic change because regardless, boxstarter does handle the error and will install the remaining updates which looked to be the case in @SurajGupta' log. However if performed "off box" it could lead to an interruption like with @kmeinster.

So give this a go and let me know how it goes.

**Closed by mwrock** 2015-04-05 03:48 UTC

**Comment by kmeinster** [comment] 2015-04-05 14:45
Nice fixes! Changed the cookbook a little bit (just the setup.bat template) at least the updates now go through as can be seen at: https://gist.github.com/kmeinster/8083315dba7bf63bbacc

So seems OK now, thanks again!

The changed template now looks like:

`@echo off`

`REM SET ps=%systemroot%\sysnative\windowspowershell\v1.0\powershell.exe`
`REM if NOT EXIST %ps% SET ps=%systemroot%\system32\windowspowershell\v1.0\powershell.exe`
`REM %ps% -NoProfile -ExecutionPolicy bypass <%= @command %>`

`powershell -NoProfile -ExecutionPolicy bypass <%= @command %>`



As you can see almost nothing changed except we now use powershell immediately :)

**Comment by SurajGupta** [comment] 2015-04-05 15:15
@mwrock - it worked!  no more error.  thanks for the insight into the bug!
