### ISSUE TITLE
why boxstarter does not reboot automatically for windows updates?

### ISSUE THREAD

**Issue by denfromufa** [mwrock/boxstarter#157] opened 2016-03-24 18:49 UTC
```
PS C:\> Install-WindowsUpdate
+ Boxstarter starting Checking for updates...
Starting windows update service
+ Boxstarter finished Checking for updates... 00:00:11.3001664
1 Updates found
+ Boxstarter starting Download of Windows 7 Service Pack 1 for x64-based Systems
 (KB976932)
+ Boxstarter finished Download of Windows 7 Service Pack 1 for x64-based Systems
 (KB976932) 00:07:54.7268084
+ Boxstarter starting Install 1 of 1 updates: Windows 7 Service Pack 1 for x64-b
ased Systems (KB976932)
+ Boxstarter finished Install 1 of 1 updates: Windows 7 Service Pack 1 for x64-b
ased Systems (KB976932) 00:03:10.4820007
Restart Required. Restarting now...
Boxstarter: Invoke-Reboot must be called from a Boxstarter package.
Stopping win update service and setting its startup type to Automatic
PS C:\>
```

**Comment by mwrock** [comment] 2016-03-24 20:59
This is really a duplicate of #11. In the meantime, `Install-WindowsUpdate` has to be called from inside a Boxstarter run.

**Closed by mwrock** 2016-03-24 20:59 UTC

**Comment by denfromufa** [comment] 2016-03-24 22:06
I thought that is the whole point of windows update feature - persistent
wrt to restarts.

**Comment by mwrock** [comment] 2016-03-24 23:03
yes but its not build as a pure command line utility. It lacks some context it needs to propperly reboot and auto login unless you run it inside a script from a Boxstarter run.
