### ISSUE TITLE
Install-BoxstarterPackage not working with multiple package

### ISSUE THREAD

**Issue by levande** [mwrock/boxstarter#165] opened 2016-04-08 11:27 UTC
I recently upgraded boxstarter from version 2.5.21 to 2.7.0 and now i´m not able to run multiple package when installing. When I try to install them separately both works.

This is the error I receive: You cannot call a method on a null-valued expression.

Could you see what I´m missing?

![image](https://cloud.githubusercontent.com/assets/11831557/14382356/700806dc-fd8d-11e5-9d91-b46c5a3dae9c.png)

**Comment by mwrock** [comment] 2016-04-08 11:42
I think this is a duplicate of #163 which I will be troubleshooting soon.

**Closed by mwrock** 2016-04-08 11:42 UTC

**Comment by levande** [comment] 2016-04-08 11:48
Ah, Thank you very much for fast reply!
