### ISSUE TITLE
ERROR: parsing "C:\ProgramData\chocolatey" - Malformed \p{X} character escape.

### ISSUE THREAD

**Issue by flcdrg** [mwrock/boxstarter#238] opened 2017-03-27 06:35 UTC
Thought I'd give 2.9.0 a spin on a new Azure VM (Windows 10).

All packages are failing with this error:

"ERROR: parsing "C:\ProgramData\chocolatey" - Malformed \p{X} character escape."

This was run using `START http://boxstarter.org/package/url?https://gist.github.com/flcdrg/87802af4c92527eb8a30/raw/7f28c4c77e3bf85346a813269cd8529ade8d1f65/boxstarter-bare.txt`

log file coming soon

**Comment by flcdrg** [comment] 2017-03-27 06:38
[boxstarter.zip](https://github.com/mwrock/boxstarter/files/871628/boxstarter.zip)

**Comment by mwrock** [comment] 2017-03-27 17:55
Looks like a bug in choco beta that has been fixed in the beta released yesterday. I'm in the midst of deploying 2.9.2 that includes that.

**Closed by mwrock** 2017-03-27 17:55 UTC

**Comment by mwrock** [comment] 2017-03-27 18:15
Note that while I have confirmed the new beta fixes this issue, it seams that the updated chocolatey.dll in boxstarter 2.9.2 does not update the internal chocolatey powershell helpers. So in order to fully get the fix, make sure to delete c:\programdata\chocolatey\helpers before running boxstarter 2.9.2.
