### ISSUE TITLE
Boxstarter interferes with chocolatey V.Next

### ISSUE THREAD

**Issue by aronovgj** [mwrock/boxstarter#96] opened 2015-06-13 21:40 UTC
I've read somewhere that the one used in Boxstarter and the new one should not interfere, as Boxstarter installs its own version in a separate folder, but they do. 
I couldn't figure out what exactly is the problem but I can tell you some symptoms:

1)
Install-ChocolateyShortcut doesn't work anymore
2) 
`The chocolatey gods have answered your request!` 
appears after install (this was removed in the new chocolatey)

I'm sure there might be some more problems.

Reproduce:
- Install Boxstarter
- Install the newest chocolatey
- Try to install this package:
https://chocolatey.org/packages/crystaldiskinfo/6.5.1

Reproduced it on 2 different VMs and on my working machine.
Getting the new chocolatey to work properly again works by reinstalling it using the install command from the chocolatey page.

**Comment by mwrock** [comment] 2015-06-22 00:00
I've been unable to reproduce this after several attempts with slightly different variations. Let me explain the exact steps I took:

1. Started with a clean win 8.1 os with nothing installed
2. Went to http://boxstarter.org and clicked the download button
3. Opened the download and invoked the `setup.bat`
4. After the boxstarter install, I opened a new PS window as admin and ran `choco upgrade chocolatey` (The boxstarter installer will install the newest version of choco if there is no choco installed)
5. To be safe I closed this window and opened a new admin PS window and ran `choco install crystaldiskinfo`

I ran a few variations of this. Can you more precisely explain your repro steps?

Thanks!

**Comment by aronovgj** [comment] 2015-06-22 00:07
might have gotten the order wrong (not sure yet, have to retry), sorry. 
1) install newest chocolatey
2) install boxstarter
3) install package

i'll try this tomorrow or so and will give you some more details.

**Comment by mwrock** [comment] 2015-06-22 00:12
OK. let me know. Its important to know exactly how you are installing boxstarter (web installer, download from site, installing choco packages) and also how you are installing choco (the install command from the web or upgrading the version installed by boxstarter).

Thanks again.

**Comment by aronovgj** [comment] 2015-06-22 13:03
ok, so:
in win7
1) install chocolatey 
`@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin`
2) download zip from boxstarter.org, unzip, execute .bat, let it install
3) install `choco install crystaldiskinfo` (installation seems to work now, not sure why. the problem was with the unmoderated newest version but the unmodereated version is down now. will have to repush it.)

output:
`... crystaldiskinfo has finished successfully! The chocolatey gods have answered your request! ...`

this chocolatey gods thing is from old chocolatey and should not be there at all, since i installed it using 0.9.9.7. 

so i can't reproduce the error at the moment but you can still see a mix-up of stuff that is in different chocolatey versions which might cause problems.

**Comment by mwrock** [comment] 2015-06-24 16:19
Yeah I see this now. I need to put the version of chocolatey that boxstarter uses outside of programdata. Working on that. Thanks

**Comment by mwrock** [comment] 2015-07-01 06:10
this should be fixed in the latest release 2.5.1.

**Closed by mwrock** 2015-07-01 06:10 UTC
