### ISSUE TITLE
Boxstarter forces reinstall and bootloop

### ISSUE THREAD

**Issue by flatlinebb** [mwrock/boxstarter#264] opened 2017-06-20 01:11 UTC
Newest version of boxstarter forces each app in my gist to be reinstalled which means it never finishes and it keeps boot-looping after dotNet because it requires a reboot. The version just prior to this update from the last couple days ago didn't do this and all my scripts worked just fine so the change is on the boxstarter end. please look into this thank you.

EDIT:
Here is the gist I'm running:
http://www.massivecloudstore.com/utils/boxstarter/boxstarter_MBI_deploy2.txt

Here is a screenshot from one of the loops:
https://goo.gl/photos/UQJbF7LftrMxGamNA

And for that want to see it in action, here is a video:
https://youtu.be/OFajymBpq10

**Comment by flatlinebb** [comment] 2017-06-20 01:13
Here is a screenshot from one of the loops:
https://goo.gl/photos/UQJbF7LftrMxGamNA

**Comment by mwrock** [comment] 2017-06-20 05:47
Hmm. There is no doubt this is happening based on your screenshots but I am not able to repro locally. Can you provide a gist of the boxstarter log file located at `$env:localappdata\boxstarter\boxstarter.log`?

**Comment by flcdrg** [comment] 2017-06-20 07:11
I'm seeing the same thing. It's doing a forced install of each package - that seems to be causing problems.

**Comment by flcdrg** [comment] 2017-06-20 07:51
It's almost as if the `-f` that is being passed in to run the temporary package is being propagated down to all the other package installs.

**Comment by flatlinebb** [comment] 2017-06-20 15:08
Log file gist: (warning, it's large)
https://gist.github.com/flatlinebb/75a553f1f7e2ed9be15a4e8870922b99/raw/af78f594b485dc3b64956bde36c462d36f59c76f/boxstarter.log

**Comment by mwrock** [comment] 2017-06-20 16:12
I'm actually able to repro now as long as I use the web launcher. Curiously it does not repro if I call `install-boxstarterpackage` directly. Further the logs confirm that boxstarter is not passing the `forcr` arg to chocolatey. So I think @flcdrg is on to something thinking that chocolatey is "inheriting" the `force` of the outer package.

I have recently dropped support for the web launcher so I don't plan on investigating this much further. However there was a deployment problem with the new bootstrapped which replaces the web launcher. I'll be pushing afix for that later today.

Once that's in place, you can install boxstarter with `. { iwr -useb http://boxstarter.org/bootstrapper.ps1 } | iex; get-boxstarter -Force` and then use `install-boxstarterpackage` to invoke your gist.

**Comment by flatlinebb** [comment] 2017-06-20 16:24
Why did you drop support for the web launcher? I use that almost exclusively for new desktop deployments! Can you at least rollback the changes you made recently so it works like it used to?
Having to install boxstarter first, and then running a gist is not useful in this scenario. Unless there is a new way to do this I'm not aware of. Is there some updated documentation on this? 

Also, is there an official changelog that documents what's new with each release? I didn't have much luck finding one, and I'm not a git guru, so sorry if I missed it somewhere obvious.

**Comment by mwrock** [comment] 2017-06-20 17:41
Have a look at http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher @flatlinebb which discusses why I am retiring the click once app and also explains the work around. The bootstrapper.p1 file discussed in the post is not currently deployed but will be in a few hours.

**Comment by flatlinebb** [comment] 2017-06-20 18:45
I get this error when trying to install Boxstarter in PowerShell. Win10 Pro latest build 1703:

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\fmlocal> iex ((New-Object System.Net.WebClient).DownloadString('http://boxstarter.org/bootstrapper.ps1')); g
et-boxstarter -Force
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:1
+ iex ((New-Object System.Net.WebClient).DownloadString('http://boxstar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

get-boxstarter : The term 'get-boxstarter' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:99
+ ... ing('http://boxstarter.org/bootstrapper.ps1')); get-boxstarter -Force
+                                                     ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-boxstarter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by flatlinebb** [comment] 2017-06-20 19:07
OK, I figured out how to launch my gist using the boxstarter PS command. The problem is it doesn't handle reboots gracefully, that is it doesn't ask for the persistent user password like the web launcher used to, so I have to login manually to have it keep running after reboot.

**Comment by mwrock** [comment] 2017-06-20 19:41
It actually can handle reboots if you use the `-Credential` argument and pass the credentials of the user who should be signed in after reboot. Have a look at the commandline help `help Install-BoxstarterPackage -Full` and you will get info on all the possible arguments with examples.

**Comment by flatlinebb** [comment] 2017-06-20 19:46
This was the perfect tool the way it was. Now I have to waste time learning
new ways of working with it. It is supposed to be helpful in my dayjob, not
become my dayjob. Besides, the boot-loop issue is still present when
running from the boxstarter shell, so that's still a show stopper for me.
What can the community do to help you maintain the web launcher? Can we
donate towards the cost of the signed certificate? Would hosting my own
private version of the web launcher be possible? This is so frustrating,
when one has come to depend on it. Changes my whole workflow.

**Comment by flcdrg** [comment] 2017-06-20 20:42
Interesting. I  thought I had the same problem using the cmdlet as well as the clickonce.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by flcdrg** [comment] 2017-06-21 11:46
Yep - just confirmed.. `install-boxstarterpackage https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/raw/demo01.ps1` runs everything with (force)

**Comment by batzen** [comment] 2017-06-22 12:07
This is a major deal breaker for us.
Would be nice to get this fixed.

**Comment by flcdrg** [comment] 2017-06-22 13:55
I wonder if this is a change in how Chocolatey works with regards to propagating the Force option to dependent packages? @ferventcoder might have some insight.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ferventcoder** [comment] 2017-06-22 14:39
Hi, just became aware of this. I'm not seeing where this started to occur just yet. Is there a location that force is called?

I don't see it in your script @flatlinebb

**Comment by flatlinebb** [comment] 2017-06-22 14:42
My script doesn't call force, it must be part of boxstarter code.

**Comment by ferventcoder** [comment] 2017-06-22 14:43
@flatlinebb that's what I was thinking, but I haven't found it yet. 

I also logged https://github.com/chocolatey/choco/issues/1347, but I'm not sure it applies here. @RichiCoder1 ran into this recently.

**Comment by ferventcoder** [comment] 2017-06-22 14:49
> This was the perfect tool the way it was. Now I have to waste time learning
new ways of working with it.

@flatlinebb I understand your frustration here, but please be considerate of others and ensure the tone doesn't lean towards negativity. Remember this is a free service that is offered that has real costs.

**Comment by batzen** [comment] 2017-06-22 16:26
@ferventcoder 
The problem is the following:
Boxstarter calls `chocolatey install $bootstrapPackage -source $source -force:$force -execution-timeout 86400` in `Invoke-ChocolateyBoxstarter.ps1` to install the desired boxstarter package.
Chocolatey or boxstarter now seems to pass `-f` to every package that gets installed during the installation of the boxstarter package. This seems to have change in choco version 0.10.6, 0.10.6.1 or 0.10.7 and/or in boxstarter 2.9.24 or 2.9.26, i guess.
Boxstarter 2.9.14 referenced choco 0.10.5 and everything works as expected.

**Comment by mwrock** [comment] 2017-06-22 16:30
My inclination is to think this is an impact from upgrading choco from 0.10.5 to 0.10.7 because that is really all that has changed between these boxstarter releases. Boxstarter logs in the debug output exactly which arguments it passes along to chocolatey and based on the logs from @flatlinebb I don't see `force` being passed. However, the "outer" package that boxstarter installs - the one that contains the gist script - is installed via `--force` so I'm wondering if chocolatey is stashing that in the shell environment and therefore propogating it to the "inner" installs.

I have not had time to probe much deeper. Its odd that I can't repro either in a normal powershell run or in the boxstarter shell and only via the click once installer. However I totally believe @flatlinebb and @flcdrg who have reported this issue outside of the click once installer.

I may revert to choco 0.10.6 and more likely to 0.10.5 to fix this quickly while we investigate further. That may reintroduce other regressions but this one is particularly aggregious.

**Comment by batzen** [comment] 2017-06-22 16:31
@mwrock I can reproduce this with the following package-content `choco install sysinternals -y`. That one line is enough to reproduce the forced install for sysinternals every time in run the package.

**Comment by mwrock** [comment] 2017-06-22 16:33
thanks. how are you invoking boxstarter @batzen ?

**Comment by batzen** [comment] 2017-06-22 16:34
@ferventcoder Maybe it's this commit as `force` is also stored in the configuration, which got recreated in the past and was thus missing the outer value of `force`. As the configuration now gets reused, everything in it is reused.
https://github.com/chocolatey/choco/commit/5ace6fdd63c1cfdf1448e930e279061db7ff0500

**Comment by batzen** [comment] 2017-06-22 16:35
@mwrock `Install-BoxstarterPackage -PackageName .\boxstarter.txt -Verbose`

**Comment by ferventcoder** [comment] 2017-06-22 16:45
@batzen @mwrock Note that I posted a link to https://github.com/chocolatey/choco/issues/1347. This issue is definitely caused by https://github.com/chocolatey/choco/issues/1296, but why it is not resetting based on what I looked through is what I'm curious about. 

`ensure_original_configuration()` should be resetting it to a base config - https://github.com/chocolatey/choco/commit/5ace6fdd63c1cfdf1448e930e279061db7ff0500#diff-558fc8759c7b76bb864e0dd9ef947b87R315

**Comment by Skolzack** [comment] 2017-07-18 17:33
I'm with the same issue, forcing reinstall and bootloop.. it's an issue from choco or what? I just can't 100% run my script :(

**Comment by ferventcoder** [comment] 2017-07-18 18:20
@Skolzack looks like there is some residual effect of the first setting in boxstarter applying to the rest of the choco configuration.

**Comment by Skolzack** [comment] 2017-07-18 18:40
So @mwrock needs to fix it? I just can't run my script cuz it bootlops :/

**Comment by ferventcoder** [comment] 2017-07-18 18:58
Go back a version or two and I think you will be fine.

**Comment by Skolzack** [comment] 2017-07-18 19:02
@ferventcoder How I can do that? I Just run http://boxstarter.org/package/nr/url?http://xxxx and it starts.

**Comment by Skolzack** [comment] 2017-07-19 13:49
I used Install-BoxstarterPackage and still bootloop. @mwrock any help?

**Comment by mwrock** [comment] 2017-07-19 14:04
This is due to the above-mentioned issue in chocolatey. Nested calls to Choco install are retaining the parent package's -force.

I'd recommend usinga previous version of boxstarter that uses Choco 0.10.5. I may release a new boxstarter that rolls back it's Choco library.

**Comment by Skolzack** [comment] 2017-07-19 14:23
@mwrock Okay, I'll wait for the new version of boxstarter. Thanks.

**Comment by mwrock** [comment] 2017-07-23 00:56
Just deployed v2.10.0 which reverts choco to 0.10.5.

**Closed by mwrock** 2017-07-23 00:56 UTC

**Comment by Skolzack** [comment] 2017-07-23 00:57
Nice! Thank you @mwrock, you definitely rocks!

**Comment by flatlinebb** [comment] 2017-07-23 01:09
Just to confirm, this fixes the forced reinstall issue? 
You never commented on the offer to help pay for the certificate and hosting fees for the web launcher by the community.

**Comment by mwrock** [comment] 2017-07-23 01:24
Yes this fixes that issue. 

I really don't want to devalue your concerns or misunderstand your use case, but I honestly believe the powershell based installer provides all the value that the web installer used with less cost and overhead.

I know its always painful to adjust your own code and workflow to accommodate deprecated features and I apologize for that inconvenience. If there is a feature in the web installer that you don't think the powershell installer accommodates please file an issue so we can patch that up.

**Comment by shamp00** [comment] 2017-07-24 15:13
Works great for me now. Thanks!

**Comment by martijnburgers** [comment] 2017-07-30 13:28
Yes I also can confirm version 2.10.3 works (coming from  2.9.26). Thanks!!!

It would help if the 2.10.x boxstarter packages are approved because now you are getting 2.9.26.

**Comment by ferventcoder** [comment] 2017-07-31 03:03
@martijnburgers the boxstarter packages are trusted, so only automated checks would hold up acceptance until a maintainer fixes the package. This looks to be the current state of the last two releases - https://chocolatey.org/packages/boxstarter/2.10.0

@mwrock can you take a closer look? You might also check your email filters in case it filtered those messages.

**Comment by mwrock** [comment] 2017-07-31 04:17
According to https://chocolatey.org/packages/boxstarter/2.10.0, it has passed automated testing but is awaiting approval. Is there maybe an issue with the trusted workflow?

**Comment by flcdrg** [comment] 2017-07-31 04:41
That package is failing automated testing. Here's what I presume is the problem from the log:

> 2017-07-23 01:32:14,867 2216 [DEBUG] - Running 'ChocolateyScriptRunner' for BoxStarter.Common v2.10.0 with packageScript 'C:\ProgramData\chocolatey\lib\BoxStarter.Common\tools\chocolateyinstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\BoxStarter.Common', installArguments: '', packageParameters: '',
> 2017-07-23 01:32:14,915 2216 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\BoxStarter.Common\tools\chocolateyinstall.ps1'
> 2017-07-23 01:32:15,180 2216 [INFO ] - C:\ProgramData\Boxstarter
> 2017-07-23 01:32:15,211 2216 [INFO ] - C:\ProgramData\Boxstarter\BuildPackages
> 2017-07-23 01:32:21,602 2216 [INFO ] - Microsoft.PowerShell.Commands.Internal.Format.FormatStartData
> 2017-07-23 01:32:21,617 2216 [INFO ] - Microsoft.PowerShell.Commands.Internal.Format.GroupStartData
> 2017-07-23 01:32:21,664 2216 [INFO ] - Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData
> 2017-07-23 01:32:21,680 2216 [INFO ] - Microsoft.PowerShell.Commands.Internal.Format.GroupEndData
> 2017-07-23 01:32:21,680 2216 [INFO ] - Microsoft.PowerShell.Commands.Internal.Format.FormatEndData
> 2017-07-23 01:32:21,696 2216 [ERROR] - ERROR: You cannot call a method on a null-valued expression.
>  at PersistBoxStarterPathToEnvironmentVariable, C:\ProgramData\chocolatey\lib\BoxStarter.Common\tools\Setup.ps1: line 104
> at Install-Boxstarter, C:\ProgramData\chocolatey\lib\BoxStarter.Common\tools\Setup.ps1: line 19
> at <ScriptBlock>, C:\ProgramData\chocolatey\lib\BoxStarter.Common\tools\chocolateyinstall.ps1: line 7
> at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 48
> at <ScriptBlock>, <No file>: line 1

**Comment by flcdrg** [comment] 2017-07-31 04:47
2.10.3 failed because at the time the validation ran, boxstarter.common 2.10.3 didn't exist. That could be a timing thing - you probably want to make sure you submit the packages to Chocolatey.org in 'leaf' order (if you get what I mean). I'm going to kick the validator for that version and see if it comes good (or if it has the same problem as 2.10.0)

**Comment by flcdrg** [comment] 2017-07-31 06:17
and 2.10.3 passed automated testing - auto approved.

**Comment by Skolzack** [comment] 2017-07-31 14:14
@mwrock Is Boxstarter Web using the old or new chocolatey version? Cuz i ran my script and it's forcing the packages install.

**Comment by mwrock** [comment] 2017-07-31 17:31
Thanks @flcdrg! I'll adjust my deployment to be more explicit in the order it pushes the packages.

**Comment by ferventcoder** [comment] 2017-07-31 17:33
The verifier typically waits 30 minutes from push time, but that doesn't always mean the indexes are fully ready to go by then.

**Comment by mwrock** [comment] 2017-07-31 17:56
@Skolzack The boxstarter web launcher is [deprecated](http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher) and will not be updated past v2.9

The best way to install and run boxstarter now is to install with the bootstrapper:

```
. { iwr -useb http://boxstarter.org/bootstrapper.ps1 } | iex; get-boxstarter -Force
```
and then install packages/gists via:
```
Install-BoxstarterPackage -PackgeName https://gist.githubusercontent.com/mwrock/5e483f46cd15791970bdd3dd221dc179/raw/2632913a757570b576b9945ed04f94b747355b69/gistfile1.txt -DisableReboots
```
