### ISSUE TITLE
Forcing Reinstall

### ISSUE THREAD

**Issue by Skolzack** [mwrock/boxstarter#276] opened 2017-07-18 16:02 UTC
How I can ignore the already installed packages? Cuz when it reboots, boxstarter force reinstall the packages again and bootloop.. there's any way to ignore the installed packages?

My script: https://raw.githubusercontent.com/nibodev/machineSetup/master/Boxstarter.MachineSetup.ps1

Thx.

**Comment by ferventcoder** [comment] 2017-07-18 18:59
Duplicate of #264

**Closed by ferventcoder** 2017-07-18 18:59 UTC
